import $mAppConfig from './appConfig.js'

//语言包
const LANGUAGE = {
	chs: {
		//公共语言包
		application: {
			appName: $mAppConfig.appName[$mAppConfig.language],
			welcomeTo: '欢迎来到' + $mAppConfig.appName[$mAppConfig.language],
			moneySymbol: '￥',
			shareTitle: '为您挑选了一个好物',
			bargainShareTitle:'我发现了好货,快来帮我砍价',
			bargaiDetailShareTitle: '好物一起砍，省钱又开心',
			wholesaleShareTitle:'邀请您参与拼团',
			wholesaleDetailShareTitle:'这里有好货，一起拼团吧',
			discountShareTitle:'限时折扣活动进行中，速来围观',
			groupShareTitle:'分享给你一个团购秒杀产品，速抢',
			appCloseContent: '商城正在维护中...',
			guessYouLike: '猜你喜欢',
			searchHold: '搜宝贝',
			needOprationInWechat: '请在微信内进行相关操作',
			needSetWechatAppid:'请先设置微信公众号APPID',
			loginOrRegist: '登录/注册',
			loginRequired: '您的登录状态已过期，请重新登录',
			confirm: '确认',
			cancel: '取消',
			reset: '重置',
			select: '选择',
			selectAll: '全选',
			'delete': '删除',
			deleteAll: '全部删除',
			deleteSelected: '删除选定',
			collection: '收藏',
			read: '已读',
			pressSaveImage: '长按图片保存到相册',
			unit: '件',
			gotIt: '我知道了',
			times: '次',
			anonymous: '匿名',
			left: '剩余',
			finished: '结束',
			defaultSkuName: '默认款',
			or: '或',
			and: '加',
			modalTitle:'提示',
			copySuccess:'已复制到剪贴板',
			shareUrlCopySuccess:'分享链接已复制到剪贴板',
			more:'更多',
			wxshareTip:'请点击右上角进行分享',
			siteCloseTitle:'应用维护中',
		},
		//组件语言包
		shopAttrContent: {
			store: '库存',
			piece: '件',
			selected: '已选',
			quantity: '购买数量',
			addToCart: '加入购物车',
			buyNow: '立即购买',
			specificationsTip: '请选择商品规格',
			outOfStock: '库存不足',
		},
		shopProductList: {
			paidNumber: '人付款',
			notSaleTip: '商品暂时不可出售',
			outOfStock: '库存不足',
			addToCartSuccessTip: '加入购物车成功',
			point:'积分',
		},
		//页面语言包
		index: {
			titleIndex: '首页',
			liveClass:'人气直播',
			wholesaleClass: '爆款拼团',
			newProductClass: '新品上市',
			recommendClass: '推荐商品',
			hotClass: '热门商品',
			liveProgress:'直播中',
			liveFinished:'已结束',
			liveStart:'开播时间:',
			launchMiniProgramError:'打开微信小程序失败',
			getWeixinServiceError:'获取微信服务失败',
			notInWechatOrApp:'请在微信小程序或者APP中打开微信直播',
			virtualVerificationVerifySuccess:'核销成功',
			scanError:'扫码失败:',
			scanMpError:'不能识别的二维码',
		},
		cart: {
			titleCart: '购物车',
			complete: '完成',
			manage: '管理',
			cartEmpty: '空空如也,随便逛逛',
			cartEmptyTip: '购物车空空如也',
			cartTotal: '购物车共 {0} 件商品',
			gift: '赠品',
			invalid: '失效',
			invalidProduct: '产品失效',
			invalidClear: '清空失效',
			total: '合计：',
			buy: '结算',
			defaultSkuName: '默认款',
			notSale: '商品暂时不可出售',
			outOfStock: '库存不足',
			clearCartConfirm: '您确定要清空购物车吗？',
			clearinvalidConfirm: '您确定要清空过期商品吗？',
			deleteCartConfirm: '您确定要删除选择的商品吗？',
			deleteCurrentCartConfirm: '您确定要删除当前商品吗？',
		},
		category: {
			titleCategory: '分类',
		},
		discover: {
			titleDiscover: '商学院',
			cateTitle:'兴趣圈',
			article:'文章',
			share:'分享',
			download:'下载',
			collect:'收藏',
			downloading:'正在为您下载，请耐心等待',
			cancelDownload:'取消下载',
		},
		profile: {
			titleProfile: '我的',
			balance: '余额',
			point: '积分',
			coupon: '优惠券',
			cart: '购物车',
			myOrder: '我的订单',
			unpaid: '待付款',
			paid: '待发货',
			shipping: '待收货',
			evaluate: '评价',
			afterSales: '售后',
			promotionCenter: '推广中心',
			totalCommission: '累计佣金',
			leftCommission: '可用佣金',
			frozenCommission:'未结算佣金',
			outCommission: '已提现',
			frozenCommissionTip:'未结算佣金是指未结算、未到账、提现中(未到账)、或其它情况下的未入账佣金部分。',
			myFootprint: '我的足迹',
			goShopping: '先去逛逛~',
			tools: '常用功能',
			recharge:'充值',
			couponCenter: '领劵中心',
			addressManage: '地址管理',
			virtualCode: '虚拟码',
			myWholesale: '我的拼团',
			myBargain: '我的砍价',
			myCollection: '我的收藏',
			live: '直播',
			hotline:'热线',
			hotlineEmpty:'暂无联系方式',
			setting: '设置',
		},
		login: {
			titleLogin: '登录',
			titlePasswordLogin:'密码登录',
			titleAuthLogin:'授权登录',
			welcomLogin: '欢迎登录',
			mobileHolder: '请输入手机号码',
			passwordHolder:'请输入登录密码',
			mobileLoginTips: '未注册的手机号验证后自动创建账号',
			passwordLoginTips:'绑定或使用手机号注册并且设置密码的用户可使用密码登录',
			mobileError: '手机号码不对啊~',
			passwordLabel:'密码',
			passwordError:'请输入登录密码',
			mobileLogin:'手机号登录/注册',
			passwordLogin: '密码登录',
			getProblem: '遇到问题？',
			passwordLoginSumbit:'密码登录',
			wechatAuthLoginSubmit:'微信授权登录',
			getCaptcha: '获取短信验证码',
			getCaptchaLater: '{0}秒后获取验证码',
			wechatLogin: '微信',
			qqLogin: 'QQ',
			appleLogin:'Apple',
			uninstallWechatAuthService:'未安装微信登录授权服务',
			uninstallIosAuthService:'未安装苹果登录授权服务',
			getWechatAuthServiceError:'获取微信登录授权服务失败',
			getIosAuthServiceError:'获取苹果登录授权服务失败',
			getWechatAuthInfoError:'获取微信登录授权失败',
			getIosAuthInfoError:'获取苹果登录授权失败',
			getAuthServiceError:'获取授权服务失败',
			wechatLoading:'微信登录中...',
			iosLoading:'苹果登录中...',
			userAgreement: '用户协议',
			privacyAgreement: '隐私政策',
			loginAgree: '登录代表您同意',
			grantAuthorization: '并授权使用您的{0}账号信息（如昵称、头像）以便统一管理',
		},
		loginCode: {
			titleCode: '获取验证码',
			inputCode: '请输入验证码',
			codeSendTo: '验证码已发送至{0}',
			codeSend:'验证码已发送',
			noCaptcha: '没有收到验证码？点我重新发送',
			getCaptchaLater: '{0}秒后获取验证码',
			mobileError: '手机号码不对啊~',
		},
		thirdPartyLogin:{
			titleLogin: '绑定手机',
			welcomLogin: '绑定手机号',
			labelMobile:'手机号',
			labelCode:'验证码',
			mobileHolder: '请输入手机号码',
			codeHolder: '请输入验证码',
			mobileLoginTips: '第三方登录请绑定新的手机号或已注册的手机号',
			mobileError: '手机号码不对啊~',
			codeError:'请输入手机验证码',
			getCaptcha: '获取验证码',
			getCaptchaLater: '{0}秒后获取验证码',
			submit:'绑定手机号并登录',
			mpSubmit:'微信手机号一键授权',
			mpLoginTips:'您可以使用微信一键授权手机号绑定并登录',
			codeLoading:'正在获取验证码...',
			authLoading:'正在获取授权...',
			getWechatAuthServiceError:'获取微信授权服务失败',
			getWechatAuthInfoError:'获取微信手机授权失败',
		},
		wechatLogin:{
			titleLogin: '公众号登录',
			login:'微信授权中，请稍候',
			error:'微信授权失败，请点击重试',
		},
		bindMobile:{
			titleBindMobile:'绑定手机号',
			labelMobile:'手机号',
			labelCode:'验证码',
			mobileHolder: '请输入手机号码',
			codeHolder: '请输入验证码',
			mobileError: '手机号码不对啊~',
			codeError:'请输入手机验证码',
			getCaptcha: '获取验证码',
			getCaptchaLater: '{0}秒后获取验证码',
			bindError:'已绑定手机号，请不要重复绑定',
			submit:'绑定手机号码',
		},
		modifyMobile:{
			titleModifyMobile:'修改手机号',
			labelMobileOld:'原手机号',
			labelMobile:'新手机号',
			labelCode:'验证码',
			mobileHolder: '请输入手机号码',
			codeHolder: '请输入验证码',
			mobileError: '手机号码不对啊~',
			codeError:'请输入手机验证码',
			getCaptcha: '获取验证码',
			getCaptchaLater: '{0}秒后获取验证码',
			submitVerify:'验证原手机号',
			submit:'修改手机号码',
		},
		modifyPassword: {
			titleModifyPassword:'设置/修改密码',
			labelMobile:'手机号',
			labelCode:'验证码',
			labelPassword:'密码',
			labelConfirmPassword:'确认密码',
			codeHolder: '请输入验证码',
			passwordHold:'请输入密码',
			confirmPasswordHold:'请再次输入密码',
			codeError:'请输入验证码',
			passwordError:'密码需要6-20位',
			confirmPasswordError:'两次输入的密码不一致',
			getCaptcha: '获取验证码',
			getCaptchaLater: '{0}秒后获取验证码',
			submit:'设置/修改密码',
		},
		search: {
			titleSearch: '搜一搜',
			searchHistory: '搜索历史',
			hotSearch: '大家都在搜',
			enterKeywords: '请输入关键字',
			noRecord: '暂无搜索记录',
			noHotRecord: '暂无热门搜索',
			clearSearchHistory: '确认清空搜索历史吗？',
		},
		noticeIndex: {
			titleNotice: '公告',
			viewDetail: '查看详情',
		},
		noticeDetail: {
			titleNoticeDetail: '公告详情',
		},
		vedio: {
			titleVedio: '视频播放'
		},
		//商品列表
		productList: {
			titleProductList: '商品列表',
			sellNum: '销量',
			filter: '筛选',
			priceRange: '价格区间',
			priceRangeTip: '请输入最低价和最高价',
			lowestPrices: '最低价',
			highestPrice: '最高价',
			allCategories: '全部分类',
			brand: '品牌',
			multiple: '综合',
			priceAsc: '价格升序',
			priceDesc: '价格降序',
			all: '全部',
			newProduct: '新品',
			recommendProduct: '推荐',
			hotProduct: '热门',
			paidNumber: '人付款',
			notSale: '商品暂时不可出售',
			outOfStock: '库存不足',
			addToCartSuccess: '添加购物车成功',
			addToCart: '加入购物车',
			immediatelyBuy: '立即购买',
			selectSpec: '请选择规格',
		},
		//商品详情
		product: {
			titleProduct: '商品详情',
			productVedio: '产品视频',
			hot: '热门',
			recommend: '推荐',
			'new': '新品',
			point: '积分',
			preSaleProduct: '预售商品',
			virtualProduct: '虚拟商品',
			virtualProductTip: '该商品为虚拟产品，请注意查收产品内容或核销码',
			preSaleDeliverTime: '预计备货:{0}',
			preSaleDeliverDay: '购买商品{0}天后备货',
			collect: '收藏',
			collectSuccess: '收藏成功',
			collectCancel: '您取消了收藏',
			share: '分享',
			poster: '海报',
			posterCreating: '正在生成海报',
			posterCreateImageError: '生成图片失败',
			posterCreateError: '生成海报失败',
			shipping: '快递',
			shippingFree: '包邮',
			shippingPay: '买家自付',
			shippingInfo:'快递说明',
			monthSale: '月销',
			marketPriceInfo: '价格',
			presellRuleTitle: '预售规则',
			presellRuleInfo: '预售玩法介绍',
			presellRuleModelTitle: '预售玩法',
			presellRuleModelInfo: [
				'1.支付定金，商家根据预计发货日期进行备货；',
				'2.支付余款，商家备货完成后，买家可以在消息通知或者订单列表中支付余款；',
				'3.准备发货，商家收到余款后进行发货。',
			],
			presellRuleStep1: '预付定金',
			presellRuleStep2: '商家备货',
			presellRuleStep3: '补全余款',
			presellRuleStep4: '等待发货',
			marketingBargain: '砍价活动',
			inviteBargain: '到手',
			marketingFinished: '活动已结束',
			marketingStart: '活动即将开始',
			marketingFinish: '距结束还剩',
			marketingDiscount: '限时折扣',
			marketingDiscountTip: '优惠折扣:',
			marketingDiscountInfo: '{0}%',
			marketingGroupBuy: '团购',
			marketingGroupBuyInfo: '起购:{0}件,限购:{1}件',
			marketingWholesale: '拼团',
			marketingWholesaleNum: '{0}人团',
			marketingWholesaleSuccess: '成功拼团{0}次',
			marketingWholesaleValidTime: '{0}小时内满人成团',
			wholesaleRuleTitle: '拼团规则',
			wholesaleRuleInfo: '拼团玩法介绍',
			wholesaleRuleStep1: '团长开团',
			wholesaleRuleStep2: '邀请好友',
			wholesaleRuleStep3: '拼团成功',
			wholesaleRuleStep4: '等待发货',
			wholesaleLack: '还差{0}人成团',
			wholesaleJoinTitle: '{0}人正在拼团，可直接参与',
			wholesaleJoinInfo: '查看全部',
			wholesaleJoin: '去参团',
			wholesaleRuleModelTitle: '拼团玩法',
			wholesaleRuleModelInfo: [
				'1.全民拼团，所有用户都可直接参团或开团；',
				'2.拼团成功，指开团在规定时间内达到规定成团人数；',
				'3.拼团失败，指开团后在规定时间内未能找到相应的人数的好友参团，该团失败，系统取消该团订单，退还已支付金额。',
			],
			wholesaleBuy: '开团抢购',
			wholesaleJoinBuy:'参团购买',
			bargainBudy: '发起砍价',
			coupon: '领劵',
			overMoney: '满{0}',
			discountMoney: '减{0}',
			discountPercent: '{0}折劵',
			store: '库存',
			outOfStockTip: '库存不足，请等待补货',
			outOfStock: '库存不足',
			left: '剩余',
			member: '会员',
			memberDiscount: '会员折扣',
			memberDiscountPercent: '会员享受 {0}% 折扣',
			maxBuy: '限购',
			maxBuyPertime: '每次最多购买{0}',
			overMoneyShippingFree: '满{0}包邮',
			overPointShipping: '购买赠送{0}积分',
			overReduce: '满减',
			getPointsAfterOrder: '下单后最低可获得{0}积分',
			needPoint:'需用积分',
			needPointInfo:'同时需使用{0}积分才能购买',
			needPointTip:'需{0}积分',
			deduct: '积分抵扣',
			deductByPoints: '每件商品最多可使用{0}积分抵扣{1}元',
			deductByPointsTip: '可用{0}积分',
			exchange: '换购',
			exchangeByPoints: '积分换购',
			exchangeByPointsTip: '可使用{0}积分换购商品',
			preferential: '优惠',
			overQuantityMoney: '满{0},每{1}减{2}元',
			overQuantityDiscount: '满{0},每{1}打{2}折',
			combination: '组合套餐{0}',
			combinationTip: '套餐优惠',
			evaluate: '评价({0})',
			evaluateGoodRate: '好评率{0}%',
			evaluateDefault: '默认好评',
			evaluateView: '查看全部评价',
			evaluateEmpty: '还没有评价信息~',
			productDetail: '宝贝详情',
			reachBottom: '已经到最底了',
			onlineService: '客服',
			cart: '购物车',
			depositPay: '预付定金',
			addToCart: '加入购物车',
			addToCartSuccess: '加入购物车成功',
			directBuy: '直接购买',
			startSoon: '活动即将开始',
			alreadyOver: '活动已结束',
			groupBuy: '立即团购',
			discountBuy: '立即抢购',
			sku: '款式',
			number: '数量',
			preBuy: '预付定金({0})',
			couponDiscount: '折',
			couponCondition: '满{0}可用',
			couponRange: '限定',
			couponRangeTip: '限定指定商品可用',
			couponAll: '全场',
			couponAllTip: '全场商品可用',
			couponValidity: '领取之日起 {0} 天内有效',
			couponUseDay: '{0} 当日使用',
			couponUseRange: '{0} 至 {1}可用',
			couponUnlimited: '不限数量',
			couponLimited: '每人限领{0}张，已领{1}，剩余{2}%',
			couponGet: '立即领取',
			couponGetSuccess: '领取成功',
			choiceProductAttribute: '请选择商品参数',
			noCouponsAvailable: '暂无优惠劵可领取'
		},
		//商品评价列表
		productEvaluation:{
			ratioTip:"商品好评率 {0}%",
			title:"商品评价",
			total:'全部',
			good:'好评',
			ordinary:'中评',
			negative:'差评',
			cover:'有图',
			again:'追加评价',
			againTip:'用户 {0} 天后追评',
			explain:'商家回复'
		},
		//组合套餐
		combination:{
			combinationTitle:'组合套餐',
			changeSku:'可选规格',
			buy:'立即购买',
			savePrice:'省',
			originalPrice:'原价',
			price:'实付',
			finish:'完成',
		},
		// 砍价部分
		bargain: {
			bargainIndexTitle: '砍价活动',
			bargainListTitle:'砍价列表',
			bargainProduct: '砍价商品',
			startSoon: '活动即将开始',
			progress:'活动进行中',
			alreadyOver: '活动已结束',
			viewMore:'查看更多',
			joinNumber:'{0}人参与砍价',
			myBargain: '我的砍价',
			bargainSuccess:'还差{0}元就成功了',
			bargainerror: '砍价失败',
			bargainStatusSuccess: '砍价成功',
			bargains: '继续砍价',
			bargainReload: '再砍一个',
			bargaiInvalid: '拼团失效',
			bargaiDetailTitle: '砍一砍',
			bargaiProductTip:'我发现了好货,快来参与砍价',
			bargaiDetailTip: '我发现了好货,快来帮我砍价',
			bargaiDetail: '可砍至',
			bargaiDeingNegotiated: '正在砍价中',
			bargaiDown: '已砍',
			baragiCanAlsoCut: '元,还可以砍',
			baragiDollar: '元',
			cutPriceList: '砍价榜',	
			baveBargain: '已砍价',
			thereAre: '还有',
			bargaiCutOff:'砍掉',
			bargainDetail: '砍价详情',
			bargaiDetailfinished: '结束, 快来砍价吧',
			bargaiCallFriends: '喊好友帮你砍一刀',
			bargaiHelpCallFriends: '帮好友砍一刀',
			bargainDetailTip1: '看见砍价,随手一砍',
			bargainDetailTip2: '分享给好友,还能砍更多',
			bargainDetailTip3: '再接再厉,很快砍成功',
			bargainDetailTip4: '拔刀相助,在所不辞',
			bargainDetailTip5: '我已经使出洪荒之力',
			bargainDetailTip6: '感情深,刀法稳',
			bargainDetailTip7: '看我的一阳指,过来就是一刀',
			bargainShare: '复制分享链接成功',
			bargainEmpty: '暂无砍价记录'
		},
		// 地址
		address: {
			shippingAddress: '收货地址',
			defaultAddress: '默认',
			newReceivingAddress: '新增地址',
			wechatAddress:'微信地址',
			editAddress: '编辑收货地址',
			recipients: '收件人',
			recipientsName: '请输入收件人姓名',
			phoneNumber: '电话号码',
			addPhoneNumber: '请输入收件人电话号码',
			region: '所在地区',
			pleaseChoose: '请选择',
			pleaseChooseAddress: '请选择地址',
			detailedAddress: '详细地址',
			addDetailedAddress: '请输入详细地址',
			setDefaultAddress: '默认地址',
			delAddress: '删除收货地址',
			saveAddress: '保存地址',
			delShippingAddress: '确定要删除收货地址吗',
			successfullyDelete: '删除成功',
			addressAddedSuccessfully: '添加地址成功',
			correctRealname:'请输入收件人姓名',
			correctPhoneNumber: '请输入正确的手机号码',
			correctAddressDetails:'请输入收件详细地址',
			modifySuccessfully: '修改成功',
			intelligentIdentification: '地址识别',
			noAddress: '还没有收货地址,添加一个吧~',
			letMeToIdentify: '点我识别',
			autofillContent: '复制粘贴自动填写内容',
			noContent: '还没有内容'
		},
		//创建订单
		orderCreate: {
			titleCreateOrder: '创建订单',
			pleaseShippingAddress: '请选择收货地址',
			shopList: '商品列表',
			theDefaultParagraph: '默认款',
			issueAnInvoice: '开具发票',
			noIssueAnInvoice: '本次不开具发票',
			electronicInvoice: '电子发票',
			company: '公司',
			name: '个人',
			remark: '备注',
			setRemark: '请填写备注信息',
			ticket: '券',
			discountCoupon: '优惠券',
			pleaseDiscountCoupon: '选择优惠券',
			send: '寄',
			modeOfDistribution: '配送方式',
			selectDeliveryMode: '选择配送方式',
			give: '递',
			courierServicesCompany: '快递公司',
			pleaseCourierServicesCompany: '选择快递公司',
			carry: '提',
			storePickUpPoint: '门店自提点',
			needIntegrals:'需用积分',
			youNeedToUseIntegrals: '需要使用{0}积分',
			subtract: '减',
			usePoint: '使用{0}积分抵用{1}元',
			amountGoods: '商品金额',
			price: '￥{0}',
			discountAmount: '优惠金额',
			shippingMoney: '运费',
			freeShippingMoney: '免运费',
			invoiceAmount: '发票税费',
			givePoint: '赠送积分',
			integral: '{0}积分',
			point: '积分',
			actualPayment: '实付款',
			submitOrder: '提交订单',
			noIntegral: '积分不足',
			free: '免运费',
			notOrder: '订单不存在',
			limit: '限',
			all: '全',
			atLeast:'满{0}可用',
			useOfSomeProducts: '部分产品使用',
			useOfAllProducts: '全场产品使用',
			noCouponForNow: '暂无优惠券',
			discount: '折',
			logisticsDistribution: '快递配送',
			theBuyerToThe: '买家自提',
			doNotDiscountCoupon: '不满足优惠券使用条件',
			couponUnsupported:'套餐购买/拼团/团购下单不支持选择购物券',
			noCoupon:'暂无可用的优惠券',
			unknown: '无名',
			uncharted: '未知',
			presellTitle:'全款预定',
			presellTip:'预售产品的预定方式',
			presellOrderPay:'定金',
			presellOrderFullPay:'全款',
			logisticsClose:'快递配送暂未开启',
			giveaways:'赠品'
		},
		//订单支付
		orderPay:{
			titleOrderPay:'订单支付',
			payMoney:'支付金额',
			payLeftTime:'剩余支付时间',
			wechatPay:'微信支付',
			aliPay:'支付宝',
			quickPay:'快捷支付',
			balancePay:'余额支付',
			brokeragePay:'佣金支付',
			confirmPay:'确定支付',
			orderClosed:'订单已关闭',
			balanceLessTip:'余额不足',
			brokerageLessTip:'佣金不足',
			payTypeError:'请选择支付方式',
			balanceError:'余额不足，请选择其它支付方式',
			brokerageError:'佣金不足，请选择其它支付方式',
			payTypeDisabledError:'当前支付方式不可用',
			commissionError:'分销功能已关闭，暂时不能使用佣金支付',
			userBalance:'当前余额{0}',
			userBrokerage:'当前佣金{0}',
			userWarehouseBrokerage:'当前货款{0}',
			allinpayTip:'支付账户由通联支付进行安全托管，请放心使用',
			getCode:'获取验证码',
			getCodeLater:'{0}秒后重新获取',
			mobileLabel:'手机号',
			codeLabel:'验证码',
			realnameLabel:'真实姓名',
			idLabel:'身份证号',
			bankcardTypeLabel:'卡类型',
			bankcardDepositLabel:'储蓄卡',
			bankcardCreditLabel:'信用卡',
			bankcardLabel:'银行卡号',
			creditCardLabel:'信用卡号',
			bankcardHolderLabel:'请使用和真实姓名一致的银行卡',
			bankMobileLabel:'预留手机',
			bankcardValidateLabel:'有效日期',
			bankcardValidateHolder:'如05/20',
			bankcardCvvLabel:'安全码',
			bankcardCvvHolder:'信用卡签名处最后3位数字',
			bankcardDefaultLabel:'默认卡',
			authSubmitLabel:'安全认证',
			realnameSubmitLabel:'实名认证',
			bindcardSubmitLabel:'绑定银行卡',
			allinpayAuthContent:'您需要认证才能进行支付',
			allinpayAuthConfirmContent:'确认认证',
			allinpayBindcardContent:'您需要绑卡才能进行支付',
			allinpayBindcardConfirmContent:'确认绑卡',
			allinpayStep1:'认证',
			allinpayStep2:'实名',
			allinpayStep3:'绑卡',
			allinpayAlreadyAuth:'您之前已完成认证，系统已自动更新您的认证信息',
			authMobileError:'请输入正确的手机号',
			codeError:'请输入验证码',
			realNameError:'请输入真实姓名',
			idError:'身份证号不正确',
			bankcardError:'请输入银行卡号',
			bankcardCodeError:'请输入验证码',
			bankcardMobileError:'请输入银行预留手机号',
			bankcardValidateError:'请输入信用卡有效期',
			bankcardCvvError:'请输入信用卡安全码',
			choiceBankcard:'请选择支付卡：',
			bankcardEmpty:'暂无可用的支付卡',
			bankcardAdd:'添加支付卡',
			bankcardSendCodeTip:'验证码已发出，请输入您收到的验证码',
			bankcardPaySubmit:'确认支付',
			bankcardSendCodeError:'请输入验证码',
			payTradenoError:'交易号错误，请重试',
			payResultTip:'正在查询支付结果，请稍候...',
			payFailTip:'支付失败：',
			wxPayFailTip:'您取消了支付或者支付失败',
			wechatPayH5Tip:'微信浏览器中才能使用微信支付',
			launchMiniProgrameError:'打开微信小程序失败',
			allinpayAppWxPayFail:'您取消了支付或支付失败',
			allinpayBankCardPayCodeSended:'验证码已自动发送',
			payMethodClosed:'当前使用的支付方式已关闭',
			payNotInWechat:'该支付方式适用于公众号或微信浏览器',
			payNotInWechatMp:'该支付方式适用于微信小程序',
			payNotInH5:'该支付方式适用于H5',
			payNotInApp:'该支付方式适用于APP',
			payNotInH5OrApp:'该支付方式适用于H5或APP',
			payNotInAppOrWechatMp:'该支付方式适用于APP或微信小程序',
			payMethodNoSupported:'当前使用的支付方式暂未支持',
			openAlipayError:'打开支付宝失败',
			allinpayAlipayTip:'如果已完成支付，请点击下方按钮，系统会自动进行支付确认；支付宝支付到账较慢，请不要重复支付。',
			allinpayAlipayConfirm:'已完成支付',
			recharge:'充值',
			orderPaid:'该笔订单已支付，请不要重复支付并耐心等待支付结果',
		},
		//APP跳转小程序支付
		allinpayAppWxPay:{
			titleAllinpayAppWxPay:'微信支付',
			tip:'微信支付中...',
			errTip:'支付失败',
			completeTip:'支付完成',
			backToApp:'返回APP',
		},
		//发票
		invoice: {
			invoiceManagement: '发票管理',
			tolerant: '默认',
			invoiceTitle: '发票抬头',
			company:'公司',
			name: '个人',
			personalInvoicesHaveNoTaxNumber: '个人发票无税号',
			addInvoice: '新增发票',
			noInvoice: '暂无发票~',
			delInvoice: '确定要删除该发票吗',
			delOk: '删除成功',
			invoiceType: '发票类型',
			inputInvoiceTitle:'请输入发票抬头',
			invoiceNumber: '发票税号',
			inputInvoiceNumber:'请输入发票税号',
			setTolerant: '设为默认',
			saveTheMessage: '保存信息',
			editInvoice: '编辑发票',
			invoiceTitleError:'发票抬头不能为空',
			invoiceParagraphError:'发票税号不能为空',
			invoiceEditSuccess:'发票编辑成功',
			invoiceAddSuccess:'发票增加功能',
			invoiceHistory: '开票历史',
			orderNumber: '订单编号:',
			invoiceSum: '开票金额:',
			noInvoiceData: '您还没有开过票哦~'
		},
		//拼团
		wholesale: {
			wholesaleTitle: '拼团',
			wholesaleShare:'为您推荐了一个拼团商品，多人拼购更便宜',
			toWholesale: '去开团',
			yesGroup: '人团',
			groupPrice: '拼到价值{0}元的 '
			
		},
		wholesaleGroup:{
			wholesaleGroupTitle:'我的拼团',
			wholesaleLeftTime:'距结束还剩',
			wholesaleStart:'开团',
			wholesaleShareTip:'还差{0}人成团,去分享吧',
			wholesaleOutOfTime:'开团超时',
			wholesalePay:'等待支付',
			wholesaleSuccess:'已成团',
			wholesaleFail:'开团失败',
			wholesaleOrderTip:'共1件商品,总金额',
			wholesaleButtonPay:'去支付',
			wholesaleButtonShare:'邀请好友',
			wholesaleButtonDetail:'拼团详情',
			wholesaleButtonOrderDetail:'订单详情',
			wholesaleEmpty:'暂无拼团订单',
			wholesaleStatusAll:'全部',
			wholesaleStatusProgress:'拼团中',
			wholesaleStatusSuccess:'拼团成功',
			wholesaleStatusFail:'拼团失败',
		},
		wholesaleDetail:{
			wholesaleDetailTitle:'拼团详情',
			wholesaleDetailShare:'邀请您参与拼团',
			wholesaleNum:'{0}人团',
		},
		//团购
		group: {
			groupTitle: '团好货',
			groupShare:'分享给你一个团购秒杀产品，速抢',
			theEventIsAboutToBegin: '活动即将开始',
			surplus: '还剩',
			immediatelyRob: '立即抢'
		},
		//限时折扣
		discount: {
			discountTitle: '限时折扣',
			discountShare:'限时折扣活动进行中，速来围观',
			noTime: '活动距结束还有',
			timeOut: '本场活动已结束',
			numberOfActivities: '活动数量',
			moreActivities: '更多活动请点击查看更多',
			more: '查看更多',
			trailerGoods: '预告商品',
			activitiesOfGoods: '活动商品',
			activitiesAreBooming: '活动火爆进行中',
			trailer: '预告',
			noActivities: '暂无活动',
			notrailerActivities: '暂无预告活动',
			activitiesList: '活动列表',
			localCommodities: '本场活动商品',
			buy: '立即购买'
		},
		//我的订单
		order: {
			myOrder: '我的订单',
			integralToUse:'已用{0}积分抵用{1}元'
		},
		//优惠券
		coupon: {
			couponTitle: '领劵中心',
			couponTip: '领好劵购好品',
			couponText: '一大波免费优惠劵等你来领走',
			noThreshold: '无门槛',
			someGoodsAvailable: '部分商品可用',
			myCoupon: '我的优惠劵'
		},
		//个人中心
		user: {
			footprintTitle: '我的足迹',
			theShelves: '已下架',
			record: '暂无浏览记录',
			productTheShelves: '商品已下架',
			delProduct: '删除宝贝成功',
			noCollection: '暂无收藏记录',
			bargain: '砍价',
			discount: '折扣',
			wholesale: '拼团',
			group: '团购',
			groupTime: '团购秒杀',
			upcoming: '即将开始',
			underWay: '正在进行中',
			personalData: '个人信息',
			changePassword: '修改密码',	
			protocolRule: '协议规则',
			wipeCache: '清除缓存',
			currentVersion: '当前版本',
			feedback: '意见反馈',
			theme:'皮肤样式',
			notification : '消息推送',
			logOut: '退出登录',
			confirmLogOut: '确定要退出登录吗',
			confirmWipeCache: '确定要清除缓存吗',
			noWipeCache: '暂无缓存',
			mobile: '手机号码',	
			nickname: '昵称',
			realname:'真实姓名',
			gender: '性别',
			changeNickname: '修改昵称',
			inputNickname: '请输入昵称',
			changeRealname: '真实姓名',
			inputRealname: '请输入真实姓名',
			realnameExist:'真实姓名已设置，无法修改。如果需要修改请联系工作人员',
			changeGender: '修改性别',
			man: '男',
			woman: '女',
			modifiedDataSuccessfully: '修改资料成功',
			theAgreement: '相关协议',
			userAgreement: '用户协议',
			privacyPolicy: '隐私政策',
			fastTyping: '快速键入',
			questionsAndComments: '问题和意见',
			inputFeedbackText: '请详细描述你的问题和意见...',
			ImageSize: '图片(选填,提供问题截图,总大小10M以下)',
			previewImage: '点击预览图片',
			addImage: '添加图片',
			qqEmailMobile: 'QQ/邮箱/手机号',
			contactWithYou: '(选填,方便我们联系你 )',
			submit: '提交',
			interfaceDisplayDisorder: '界面显示错乱',
			slowStart: '启动缓慢，卡出翔了',
			UI: 'UI无法直视，丑哭了',
			accidentalCollapse: '偶发性崩溃',
			dataCalculationError: '数据计算错误',
			bugFeedback: 'BUG反馈',
			information: '业务咨询',
			feedbackTip: '感谢您的反馈，我们会尽快处理',
			feedbackType: '反馈类型',
			featureSuggestions: '功能建议',
			memberLevel:'普通会员',
			modifyMobile:'修改手机号',
			bindMobile:'绑定手机号',
		},
		//虚拟码
		virtual:{
			virtualIndexTitle:'我的虚拟码',
			virtualDetailTitle:'虚拟码详情',
			useTime:'使用次数',
			noLimit:'无限制',
		},
		//提示成功失败页面
		notice:{
			successTitle:'操作成功',
			successSub:'您可以返回上一页或者回到用户中心',
			successTip:'平台不会储存您的任何实名等相关信息。请勿泄露个人姓名、身份证号码、银行卡！谨防电话诈骗！',
			paySuccessTitle:'支付成功',
			paySuccessSub:'您可以查看订单或者回到用户中心',
			paySuccessTip:'平台不会储存您的任何实名等相关信息。请勿泄露个人姓名、身份证号码、银行卡！谨防电话诈骗！',
			payCompleteTitle:'支付结果',
			payCompleteTardeNoEmptyTitle:'订单号错误',
			payCompleteTimeoutTitle:'查询超时',
			payCompleteErrorTitle:'查询失败',
			payCompleteSuccessTitle:'支付成功',
			payCompleteFailTitle:'支付失败',
			payCompleteSub:'正在获取支付结果，请稍候...',
			payCompleteTardeNoEmptySub:'获取订单号错误，请确认订单',
			payCompleteTimeoutSub:'查询支付结果超时，请稍后在订单中心查看支付结果',
			payCompleteErrorSub:'查询支付结果失败，请稍后在订单中心查看支付结果',
			payCompleteSuccessSub:'您可以查看订单或者回到用户中心',
			payCompleteFailSub:'支付失败，您可以前往订单中心重新付款',
			payCompleteTip:'平台不会储存您的任何实名等相关信息。请勿泄露个人姓名、身份证号码、银行卡！谨防电话诈骗！',
			failTitle:'操作失败',
			failSub:'您可以返回上一页或者回到用户中心',
			failTip:'平台不会储存您的任何实名等相关信息。请勿泄露个人姓名、身份证号码、银行卡！谨防电话诈骗！',
			back:'返回',
			userCenter:'用户中心',
			viewOrder:'查看订单',
			tip:'温馨提示:',
		},
		// 分销
		distribution: {
			noName: '暂无名称',
			noLevel: '暂无级别',
			salesNumber: '销售笔数',
			theSalesAmount: '销售金额',
			toPromote: '推广',
			myTeam: '我的团队',
			straightPushOrders: '直推订单',
			teamOrders: '团队订单',
			upgradeConditions: '升级条件',
			toPromoteQrCode: '推广二维码',
			toPromotePosters: '推广海报',
			myCommission: '我的佣金',
			theCommissionSubsidiary: '佣金明细',
			iWantToWithdraw: '我要提现',
			cashAccount: '提现账号',
			withdrawalRecord: '提现记录',
			theAgent: '代理商',
			regionalAgent: '区域代理商',
			failedToLoadConfiguration: '加载配置失败',
			provincialGeneration: '省代',
			inTheGeneration: '市代',
			areaGeneration: '区代',
			myReferences: '我的推荐人',
			distributorsInAllPeople: '分销商共{0}人',
			headPortrait: '头像',
			nickname: '昵称',
			mobilePhoneNo: '手机号',
			haveToPay: '已支付',
			registrationTime: '注册时间',
			is: '是',
			theSuperiorId: '上级ID:',
			theSuperiorNickname: '上级昵称:',
			thereIsNo: '无',
			noReferences: '没有推荐人',
			noDistributorMemberAtThisLevel: '暂无该级别分销商成员',
			primaryDistributor: '一级分销商',
			secondaryDistributor: '二级分销商',
			amountOfCommissionAvailableForWithdrawal: '可提现佣金金额',
			theDetail: '明细',
			salesNumber: '销售笔数',
			theSalesAmount: '销售金额',
			immediateWithdrawal: '立即提现',
			withdrawalClosed: '提现已暂时关闭',
			type: '类型:',
			time: '时间:',
			money: '资金:',
			noBillRecordYet: '暂无账单记录',
			level3Distribution: '裂变分销',
			theStoreDistribution: '店铺分销',
			regionalDistribution: '区域分销',
			withdrawal: '提现',
			systemTopUp: '系统充值'
		},
		//充值
		recharge:{
			titleRecharge:'充值中心',
			confirmPay:'确定充值',
		}
	},
	cht: {

	},
	eng: {

	}
}

export default LANGUAGE[$mAppConfig.language];
